/*
 * This source file was generated by the Gradle 'init' task
 */
package ringbuffer;

public class App {
    public String getGreeting() {
        return "Ring Buffer Demo";
    }

    public static void main(String[] args) {
        RingBuffer<Integer> buffer = new RingBuffer<>(3);
        Reader<Integer> fastReader = buffer.createReader();
        Reader<Integer> slowReader = buffer.createReader();

        System.out.println(new App().getGreeting());
        System.out.println("Capacity: " + buffer.capacity());

        buffer.write(1);
        buffer.write(2);
        buffer.write(3);

        ReadResult<Integer> fastFirst = fastReader.read();
        ReadResult<Integer> fastSecond = fastReader.read();
        System.out.println("Fast reader reads: "
                + fastFirst.value().orElse(null)
                + ", "
                + fastSecond.value().orElse(null));

        buffer.write(4);
        buffer.write(5);

        ReadResult<Integer> slowFirst = slowReader.read();
        System.out.println("Slow reader next value: " + slowFirst.value().orElse(null));
        System.out.println("Slow reader skipped: " + slowFirst.skippedCount());

        ReadResult<Integer> fastThird = fastReader.read();
        ReadResult<Integer> fastFourth = fastReader.read();
        ReadResult<Integer> fastFifth = fastReader.read();
        System.out.println("Fast reader continues: "
                + fastThird.value().orElse(null)
                + ", "
                + fastFourth.value().orElse(null)
                + ", "
                + fastFifth.value().orElse(null));
    }
}
